# Generated by Django 5.0.4 on 2024-05-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
