# Generated by Django 5.0.4 on 2024-05-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_joblisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
