# Generated by Django 5.0.4 on 2024-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_joblisting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
