# Generated by Django 5.0.4 on 2024-06-09 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_joblisting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='experience_level',
            field=models.CharField(default='Mid', max_length=50),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='last_day_to_apply',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='remote',
            field=models.CharField(default='Hybrid', max_length=50),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
