# Generated by Django 5.0.4 on 2024-06-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_customuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
