# Generated by Django 5.0.4 on 2024-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
